server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}


app:
  storage:
    s3Endpoint: ${STORAGE_S3_ENDPOINT}
    s3Region: ${STORAGE_S3_REGION}
    s3AccessKey: ${STORAGE_S3_ACCESS_KEY}
    s3SecretKey: ${STORAGE_S3_SECRET_KEY}
    s3Bucket: ${STORAGE_S3_BUCKET}

  rabbit:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

internalJwt:
  issuer: ${INTERNAL_JWT_ISSUER}
  secret: ${INTERNAL_JWT_SECRET}
